on: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo login docker hub
      - echo Build started on `date`
      - echo Starting Unit Tests
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Writing image definitions file...
artifacts:
  files: imagedefinitions.json
